spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud?useSLL=false&serverTimeZone=UTC&jdbcCompliantTruncation=false
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect